"""Pydantic models describing one entry of ``nebulae.json``.

The models are the single source of truth for what a valid nebula looks like.
The admin API, the CLI and the tests all validate through them.
"""

from __future__ import annotations

import re
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator, model_validator

NebulaType = Literal["Emission", "Reflection", "Planetary", "Supernova remnant", "Dark"]
NEBULA_TYPES: tuple[str, ...] = NebulaType.__args__  # type: ignore[attr-defined]

SLUG_PATTERN = r"^[a-z0-9]+(?:-[a-z0-9]+)*$"
IMAGE_PATH_PATTERN = r"^images/[a-z0-9]+(?:[/-][a-z0-9]+)*$"
URL_PATTERN = r"^https?://[^\s]+$"

#: Order in which keys are written to nebulae.json (keeps diffs readable).
KEY_ORDER = (
    "id",
    "name",
    "catalog",
    "nickname",
    "type",
    "constellation",
    "distance",
    "size",
    "description",
    "facts",
    "image_path",
    "image_alt",
    "credits",
    "source_url",
    "source_page",
    "image",
)

Fact = Annotated[str, Field(min_length=1, max_length=300)]


class ImageMeta(BaseModel):
    """Generated by the image pipeline. Never edit by hand."""

    model_config = ConfigDict(extra="forbid")

    width: int = Field(gt=0, description="Width of the largest derivative, in pixels")
    height: int = Field(gt=0, description="Height of the largest derivative, in pixels")
    widths: list[int] = Field(min_length=1, description="Widths that exist on disk")
    formats: list[Literal["avif", "webp"]] = Field(min_length=1)
    placeholder: str = Field(pattern=r"^data:image/webp;base64,[A-Za-z0-9+/=]+$", max_length=4000)
    color: str = Field(pattern=r"^#[0-9a-f]{6}$")


class NebulaInput(BaseModel):
    """Fields a person edits. Sent by the admin UI on create and update."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    id: str | None = Field(default=None, pattern=SLUG_PATTERN, max_length=60)
    name: str = Field(min_length=1, max_length=80)
    catalog: str | None = Field(default=None, max_length=40)
    nickname: str | None = Field(default=None, max_length=80)
    type: NebulaType
    constellation: str = Field(min_length=1, max_length=40)
    distance: float = Field(gt=0, le=1e10, description="Distance from Earth in light-years")
    size: str = Field(min_length=1, max_length=80)
    description: str = Field(min_length=1, max_length=1200)
    facts: list[Fact] = Field(default_factory=list, max_length=8)
    image_path: str | None = Field(default=None, pattern=IMAGE_PATH_PATTERN, max_length=120)
    image_alt: str = Field(min_length=1, max_length=300)
    credits: str = Field(min_length=1, max_length=300)
    source_url: str | None = Field(default=None, pattern=URL_PATTERN, max_length=500)
    source_page: str | None = Field(default=None, pattern=URL_PATTERN, max_length=500)

    @field_validator("catalog", "nickname", "source_url", "source_page", "image_path", "id", mode="before")
    @classmethod
    def _blank_to_none(cls, value: Any) -> Any:
        if isinstance(value, str) and not value.strip():
            return None
        return value

    @field_validator("facts", mode="before")
    @classmethod
    def _drop_blank_facts(cls, value: Any) -> Any:
        if isinstance(value, list):
            return [item.strip() for item in value if isinstance(item, str) and item.strip()]
        return value

    @field_serializer("distance")
    def _serialize_distance(self, value: float) -> int | float:
        return int(value) if float(value).is_integer() else value


class Nebula(NebulaInput):
    """A complete, stored nebula."""

    id: str = Field(pattern=SLUG_PATTERN, max_length=60)
    image_path: str = Field(default="", pattern=rf"({IMAGE_PATH_PATTERN})|^$", max_length=120)
    image: ImageMeta | None = None

    @model_validator(mode="after")
    def _default_image_path(self) -> Nebula:
        if not self.image_path:
            self.image_path = default_image_path(self.id)
        return self

    def to_json(self) -> dict[str, Any]:
        """Serialise in a stable key order, leaving out empty optional fields."""
        data = self.model_dump(mode="json", exclude_none=True)
        return {key: data[key] for key in KEY_ORDER if key in data}


def default_image_path(nebula_id: str) -> str:
    return f"images/nebulae/{nebula_id}"


def slugify(text: str) -> str:
    """Turn a display name into an id: "North America Nebula" -> "north-america"."""
    text = re.sub(r"\bnebula\b", "", text.lower())
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text[:60].strip("-")
